### ISSUE TITLE
How to calculate three-phonon scattering phase space in Phono3py ?

### ISSUE THREAD

**Issue by weileiweilei** [atztogo/phono3py#16]
The description of phase space for three-phonon processes are given  in reference [J. Phys.: Condens. Matter 20 (2008) 165209] by L Lindsay et. al.,which could decide the number (space) of phonon scattering processes.

The calculation of phase space has already been implemented in ShengBTE package. I want to know that if three-phonon scattering phase space calculation can be performed in Phono3py package, and how ?
Thanks !

**Comment by atztogo** [comment]
There exists no command line interface. But it is essentially here,https://github.com/atztogo/phono3py/blob/master/phono3py/phonon3/joint_dos.py.

**Comment by weileiweilei** [comment]
> There exists no command line interface. But it is essentially here,https://github.com/atztogo/phono3py/blob/master/phono3py/phonon3/joint_dos.py.

Dear professor Togo:
Thanks for your reply. 
So, in your opinion, the  joint density of states (JDOS) are physically equal to three-phonon scattering phase space , right? Then, for JDOS and weighted JDOS, which one should I choose to perform the calculation in order to study the number (space) of phonon scattering processes? 
Thank you very much!

**Comment by atztogo** [comment]
No. You need to sample specific q-points and take sum over them for your  three-phonon scattering phase space.

> Then, for JDOS and weighted JDOS, which one should I choose to perform the calculation in order to study the number (space) of phonon scattering processes?

It's up to your will and I think depending on physical discussion. Maybe you can develop something else. Perhaps you can study and read previous papers on this topic in detail. I think this is an open question and waiting for your intelligence. Anyway, this is out of scope to discuss here, because here is to discuss the code but not physics.

Finally I consider that you'd better not to paste the paper's screenshot on public site like here unless open access one because it's copyrighted though I am not sure very much how it is strict (may depend on the amount, etc).
