### ISSUE TITLE
Compression when writing forceconstants to hdf5

### ISSUE THREAD

**Issue by erikfransson** [atztogo/phono3py#19]
Hi,
I was wondering if it is possible to use compression when writing the fc2.hdf5 and fc3.hdf5 files?
Reading the h5py documentations this seems possible. http://docs.h5py.org/en/stable/high/dataset.html#filter-pipeline

When I tried it for a 125-atom supercell, the `fc3.hdf5` file went from `400MB` to `1.5MB`.
```
w.create_dataset('fc3', data=fc3, compression='gzip')
```

**Comment by atztogo** [comment]
I updated the methods. I was afraid of the data type and order, but it seems working on my mac.

https://github.com/atztogo/phono3py/blob/982307ef63e70ee6f5b5fcd8ae2dc95c9c7393a3/phono3py/file_IO.py#L184-L231

I have to consider the user interface. Do you want to invoke it from command line option and input file setting?

I was thinking people prefer to use other similar code like almaBTE. So I didn't put my effort so much to phono3py to be more usable and robust. If demands to phono3py exist, I have to consider to improve test, API, documents, and docstring.

**Comment by atztogo** [comment]
I implemented `--hdf5-compression` option in develop branch. I can't guarantee if it works correctly or not, but for me it works well currently. The test is not enough done yet, so you may be able to find bugs. If you are interested in it, you can use like `--hdf5-compression=gzip`. I think other Lossless compression filters can be also usable because just passing the string or integer to h5py library. Many other hdf5 files data are also compressed, i.e., detailed control to compress specific hdf5 files is not supported yet. The compression of `fc2.hdf5` is not implemented (yet).

**Comment by erikfransson** [comment]
That sounds like a good solution.
I've tested it for simple cases and it works fine for me as well.

Do you think the --hdf5-compression=gzip should be the default behavior?

**Comment by atztogo** [comment]
> Do you think the --hdf5-compression=gzip should be the default behavior?

I think it is the direction. But I will use it by myself for a while until being sure that it will not make something wrong.

**Comment by erikfransson** [comment]
Thats sounds good, you can close this issue if you like.

**Comment by atztogo** [comment]
I made `--hdf5-compression=gzip` as default in the develop branch and wrote documentation https://atztogo.github.io/phono3py/command-options.html#hdf5-compression-choice-of-hdf5-compression-filter. `fc2.hdf5` is not yet compressed since the code is in phonopy but not phono3py.

**Comment by erikfransson** [comment]
Very nice!
I think its less important for the `fc2.hdf5` since it is often not that large.
