### ISSUE TITLE
phonon lifetime

### ISSUE THREAD

**Issue by Nileme** [atztogo/phono3py#30]
Dear professor Togo:
The phonon lifetime equals 1/(2X2XPIXgamma) at some temperature in some grid point, such as 300 K and L point at the website http://atztogo.github.io/phono3py/hdf5_howto.html, but in "Distributions of phonon lifetimes in Brillouin zones" paper the gamma(imaginary part of the self-energy) corresponds the formula (11) with omega and phonon ocuupation number two parameters at least. I wonder where does the first mentioned gamma come from. Does the gamma was integrated with respect to omega and phonon occupation number at temperature 300 K? I'm not sure that. Could you give me more details, such as a formula? Thank you so much.
Best wishes!

**Comment by atztogo** [comment]
I don't see what you mean but I think you can find the answer if you read the paper carefully.
I think this question is not about the detail of the code, so please send your question to the phonopy mailing list if you can not your the answer in the paper.

**Comment by Nileme** [comment]
I am sorry. Please let me say it again. The phonon lifetime is equal to 1/(2*2*PI*gamma) at some temperature and some grid point, on the website http://atztogo.github.io/phono3py/hdf5_howto.html, but in "Distributions of phonon lifetimes in Brillouin zones" paper the gamma(imaginary part of the self-energy) corresponds to equation 11, which is a formula for at least two parameters of omega and phonon ocuupation number. I don't know how the first mentioned gamma(in the phonon lifetime) was obtained. Is the gamma the integral of omega and phonon occupation number? I'm not sure about that. Can you give me more details? Thank you so much.
Best wishes!

**Comment by atztogo** [comment]
Still not clear for me. As I wrote, I want to receive this kind of question from the phonopy mailing list because this question is more shared among users. Here I suppose the issues on technical problems of the code are discussed.

>   a formula for at least two parameters of omega and phonon ocuupation number.

This is not very correct. You can read the formula straightforwardly as it is written. It's a function of \omega and \lambda. Eq.11 gives \Gamma_\lambda(\omega), where \omega is arbitrary. Lifetime is defined as 1/2\Gamma_\lambda (\omega_\lambda), where \omega_\lambda is the phonon frequency of phonon mode \lambda. Therefore this  \Gamma_\lambda(\omega) is a function of \lambda, but not \omega.

Again, please send your question to the phonopy mailing list.

**Comment by Nileme** [comment]
Thanks for your reply. Let me think about your formula again. I don't know about phonon list yet.
