### ISSUE TITLE
Obtaining phonon linewidths/lifetimes along reduced wave vector 

### ISSUE THREAD

**Issue by glensk** [atztogo/phono3py#4]
Dear Atz Togo,

You have an example at [https://atztogo.github.io/phono3py/hdf5_howto.html](https://atztogo.github.io/phono3py/hdf5_howto.html) where you nicely show how to calculate phonon linewidths and lifetimes using phono3py (following the above link, the variable "g" corresponds to the phonon linewidths and the variable "lifetime" to the phonon lifetime). Using g[:,5] one can obtain the phonon linewidths for a certain branch.  The given linewidths are, if I understand correctly, given for all the calculated q-points within the first brillouin zone. Now my question: Is it possible to obtain the linewidths for specific q-points which correspond to a certain path along a high symmetry direction of the phonon dispersion? Assuming I would like to plot the linewidths from Gamma to X (the reduced wave vector), which indizes would those points correspond to in the variable "g"? Are there any means to find out also for the other high symmetry pahts? Any help would be sincerely appreciated. Best wishes, yours,

Albert

**Comment by atztogo** [comment]
2g is FWHM. This may be important and may not be important for you.

The path in Brillouin zone (BZ). In phono3py, arbitrary q-point can't be sampled. Any q-point has to be on a grid point of the chosen uniform sampling mesh. This is a constraint of ph-ph interaction calculation, otherwise, it is difficult to satisfy q+q'+q''=G. Under knowing this constraint, you have to choose your grid points to be alined along your path and for collecting those grid points, --ga option instead of --gp option may be useful for you. The correspondence between a "ga" index set and the gp index is shown in the standard output of phono3py. Or you may find it grid_addres-xxx.hdf5 (obtained by --wgp option) inversely. If this is not convenient enough, I will write a short script to satisfy you.

Togo

**Comment by atztogo** [comment]
I will close this issue.
